# Generated by Django 3.0.6 on 2020-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadorder',
            name='contact',
        ),
    ]
