# Generated by Django 3.0.6 on 2020-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection_terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trasport_charge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
