# Generated by Django 3.0.6 on 2020-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201101_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
