# Generated by Django 3.0.6 on 2020-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_company_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadorder',
            name='company_name2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
