# Generated by Django 3.0.6 on 2020-11-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_leadorder_company_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadorder',
            old_name='order_no',
            new_name='lead_no',
        ),
    ]
