# Generated by Django 3.0.6 on 2020-10-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='trasport_charge',
            new_name='sales_person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='transport_charge',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
