# Generated by Django 3.0.6 on 2020-11-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201102_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='order_no',
            new_name='lead_no',
        ),
    ]
