# Generated by Django 3.0.6 on 2020-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201017_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_days',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
