# Generated by Django 3.0.6 on 2020-11-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201108_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='company_name2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
