# Generated by Django 3.0.6 on 2020-10-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201002_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_name',
            new_name='name',
        ),
    ]
