# Generated by Django 3.0.6 on 2020-10-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='LeadOrder',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
