# Generated by Django 3.0.6 on 2020-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201010_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='comapnay_name',
            new_name='company_name',
        ),
    ]
