# Generated by Django 3.0.6 on 2020-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201010_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_person',
            new_name='contact_person1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='contact_person2',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
