# Generated by Django 3.0.7 on 2020-10-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customercontactperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_person1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile2',
        ),
    ]
